### ISSUE TITLE
How to configure other editors than CKEditor 5, like TipTap, TinyMCE, Quill?

### ISSUE THREAD

**Issue by MacLake** [django-cms/djangocms-text#18]
Following the instruction works perfectly  for installing the package using CKEditor 5, but I am missing some more information how to go for another editor like TipTap, TinyMCE, Quill. Is it necessary to install additional packages? Okay, probably not, since they seem to be in `contrib`. What exactly do I have to add to `INSTALLED_APPS` and what do I set as `DJANGOCMS_TEXT_EDITOR` for the other editors?

Besides, the link to the CMS_PLACEHOLDER_CONF docs is dead.

**Comment by fsbraun** [comment]
Tiptap is the default config. 

Others are totally experimental.

Add `"djangocms_text.contrib.text_ckeditor5"` to installed apps and set `TEXT_EDITOR = "djangocms_text.contrib.text_ckeditor5.ckeditor5"`.

Frankly, this is supported poorly only right now.

**Comment by fsbraun** [comment]
The README needs an update.

**Comment by fsbraun** [comment]
I've updated the readme and do close this issue now.
