### ISSUE TITLE
Setting 'DJANGOCMS_TEXT_EDITOR' or 'TEXT_EDITOR' ?

### ISSUE THREAD

**Issue by sveetch** [django-cms/djangocms-text#35]
**Describe the bug**

Following README documentation i was using `DJANGOCMS_TEXT_EDITOR` to enable the `ckeditor4` but the editor 'TipTap' was still used.

Finally searching from code i found that the really used setting name was `TEXT_EDITOR`:

https://github.com/django-cms/djangocms-text/blob/df9a540a2bd1b8e79283662b4d9f2313267fca19/djangocms_text/editors.py#L438

**Environment**
Describe your environment:

- Plateform: Any
- Python version: >=3.10
- Django version: >=5.0
- djangocms-text version: 0.3.3

**Expected behavior**

The documented setting name should be used in code. I imagine this is a typo error and `DJANGOCMS_TEXT_EDITOR` is the accurate setting name.

**Comment by fsbraun** [comment]
Well spotted! Thanks for pointing this out. I just fixed the README file.
