### ISSUE TITLE
RTEConfig for 'ckeditor4' is loading 'ckeditor.js' from a wrong path 

### ISSUE THREAD

**Issue by sveetch** [django-cms/djangocms-text#38]
**Describe the bug**

When loading a page in edit mode there is a 404 response from a request to `/static/djangocms_text/vendor/ckeditor4/ckeditor.js`.

From what i've searched it seems that this is a path defined in the RTEConfig:

https://github.com/django-cms/djangocms-text/blob/6ce2d5f00286b3a9ff9f856f9258f82e681fa715/djangocms_text/contrib/text_ckeditor4/__init__.py#L8

A script tag using this wrong url path can be seen in the page DOM.

However it has surprised me that this request failure does not break the editor, it still works perfectly well without any error when using it.

**Environment**

- Plateform: Any
- Python version: Python 3.10
- Django version: Django 5.0.10
- DjangoCMS version: Django 4.1.4
- djangocms-text version: 0.3.3

**To Reproduce**
1. Install djangocms-text in a barebone DjangoCMS 4.1 project
2. Enable the editor 'ckeditor4'
3. Go to edit a page
4. See in browser inspector for requests
5. A request to `/static/djangocms_text/vendor/ckeditor4/ckeditor.js` fail with a 404 response

**Expected behavior**

There should not be any 404 response from application assets.

I suppose it should rather point to this file instead : https://github.com/django-cms/djangocms-text/blob/main/djangocms_text/static/djangocms_text/js/ckeditor4.js ?

**Comment by fsbraun** [comment]
@sveetch Nice catch. All the code for the ckeditor is contained in the bundle. The marked line is not necessary and should be removed. What to create a PR?

**Comment by sveetch** [comment]
Well i've just tried to build a fix just removing the line pointing to unexisting path and then i got many error in console output.  Then i've tried to use the path `djangocms_text/js/ckeditor4.js` instead of `djangocms_text/vendor/ckeditor4/ckeditor.js` and i got almost the same errors:

```
POST
http://192.168.0.105:8001/en/admin/djangocms_versioning/pagecontentversion/1/edit-redirect/
[HTTP/1.1 302 Found 15ms]

GET
http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/
[HTTP/1.1 200 OK 219ms]

GET
https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
[HTTP/3 200 OK 0ms]

GET
http://192.168.0.105:8001/static/djangocms_text/css/cms.text.css
[HTTP/1.1 200 OK 0ms]

GET
http://192.168.0.105:8001/static/cms/css/4.1.4/cms.base.css
[HTTP/1.1 200 OK 0ms]

GET
http://192.168.0.105:8001/static/djangocms_text/css/cms.ckeditor4.css
[HTTP/1.1 200 OK 0ms]

GET
https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
[HTTP/3 200  0ms]

GET
http://192.168.0.105:8001/static/djangocms_text/bundles/bundle.editor.min.js

GET
http://192.168.0.105:8001/static/cms/js/dist/4.1.4/bundle.toolbar.min.js
[HTTP/1.1 200 OK 0ms]

GET
http://192.168.0.105:8001/static/djangocms_text/bundles/bundle.ckeditor4.min.js
[HTTP/1.1 200 OK 0ms]

GET
http://192.168.0.105:8001/static/djangocms_text/js/ckeditor4.js
[HTTP/1.1 200 OK 0ms]

GET
http://192.168.0.105:8001/favicon.ico
[HTTP/1.1 302 Found 17ms]

undefined cms.ckeditor4.js:100
GET
http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/config.js?t=N2M9
NS_ERROR_CORRUPTED_CONTENT

La ressource à l’adresse « http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/config.js?t=N2M9 » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). 1
Échec du chargement pour l’élément <script> dont la source est « http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/config.js?t=N2M9 ». 1:1:1
GET
http://192.168.0.105:8001/en/favicon.ico/
[HTTP/1.1 404 Not Found 0ms]

GET
http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/skins/moono-lisa/editor_gecko.css?t=N2M9
NS_ERROR_CORRUPTED_CONTENT

GET
http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/lang/en.js?t=N2M9
NS_ERROR_CORRUPTED_CONTENT

La ressource à l’adresse « http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/lang/en.js?t=N2M9 » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). 1
Échec du chargement pour l’élément <script> dont la source est « http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/lang/en.js?t=N2M9 ». 1:1:1
Uncaught TypeError: c[a] is undefined
    d ckeditor.js:260
    x ckeditor.js:261
    y ckeditor.js:261
    A ckeditor.js:261
    onerror ckeditor.js:262
    F ckeditor.js:262
    load ckeditor.js:263
    load ckeditor.js:260
    m ckeditor.js:279
    p ckeditor.js:279
    b ckeditor.js:567
    loadPart ckeditor.js:569
    p ckeditor.js:279
    h ckeditor.js:278
    m ckeditor.js:10
    fire ckeditor.js:12
    fire ckeditor.js:13
    fireOnce ckeditor.js:12
    fireOnce ckeditor.js:13
    k ckeditor.js:276
    k ckeditor.js:276
    callback ckeditor.js:263
    x ckeditor.js:261
    y ckeditor.js:261
    A ckeditor.js:261
    onerror ckeditor.js:262
    F ckeditor.js:262
    load ckeditor.js:263
    a ckeditor.js:263
    queue ckeditor.js:263
    k ckeditor.js:276
    h ckeditor.js:278
    a ckeditor.js:275
    setTimeout ckeditor.js:30
    setTimeout handler*setTimeout ckeditor.js:30
    a ckeditor.js:275
    inline ckeditor.js:365
    create cms.ckeditor4.js:99
    init cms.editor.js:129
    observer cms.editor.js:159
    observer cms.editor.js:157
    initInlineEditors cms.editor.js:156
    initAll cms.editor.js:61
    CMSEditor cms.editor.js:42
    CMSEditor cms.editor.js:21
    <anonymous> cms.editor.js:653
    <anonymous> bundle.editor.min.js:765
ckeditor.js:260:45
La ressource à l’adresse « http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/edit/1/skins/moono-lisa/editor_gecko.css?t=N2M9 » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). 1
styles 
NodeList []
cms.ckeditor4.js:112
XHRGET
http://192.168.0.105:8001/en/admin/cms/placeholder/object/10/structure/1/
[HTTP/1.1 200 OK 75ms]
```

Is it me or does the ckeditor try to directly load some assets relatively to `/en/admin/cms/placeholder/object/10/edit/1/` ?

That is pretty strange because i did not have any errors with the wrong path (`djangocms_text/vendor/ckeditor4/ckeditor.js`) leading to a 404 and the editor still work fine..

**Comment by fsbraun** [comment]
Interesting. That might be an additional issue (which we potentially can sole on one go). It might be that a static path is not passed on to the ckeditor4 js.

**Comment by fsbraun** [comment]
@sveetch Is `cmsplugins.svg` loaded successfully ( the puzzle icon that heads the cms plugin dropdown)?

**Comment by fsbraun** [comment]
Another quick thought: What if you replaced the `djangocms_text/vendor/ckeditor4/ckeditor.js` by `ckeditor4/ckeditor.js`? (That's the correct path but loads the editor twice - for now, I am just curious if skins etc load correctly)
